Date.now||(Date.now=function(){return(new Date).getTime()});
(function(){for(var a=["webkit","moz"],c=0;c<a.length&&!window.requestAnimationFrame;++c){var b=a[c];window.requestAnimationFrame=window[b+"RequestAnimationFrame"];window.cancelAnimationFrame=window[b+"CancelAnimationFrame"]||window[b+"CancelRequestAnimationFrame"]}if(/iP(ad|hone|od).*OS 6/.test(window.navigator.userAgent)||!window.requestAnimationFrame||!window.cancelAnimationFrame){var e=0;window.requestAnimationFrame=function(a){var c=Date.now(),b=Math.max(e+16,c);return setTimeout(function(){a(e=
b)},b-c)};window.cancelAnimationFrame=clearTimeout}})();var supportsPassive=!1;try{var opts=Object.defineProperty({},"passive",{get:function(){supportsPassive=!0}});window.addEventListener("testPassive",null,opts);window.removeEventListener("testPassive",null,opts)}catch(e$$12){};(function(a,c){"object"===typeof exports&&"undefined"!==typeof module?module.exports=c():"function"===typeof define&&define.amd?define(c):a.Stats=c()})(this,function(){var a=function(){function c(a){k.appendChild(a.dom);return a}function b(a){for(var c=0;c<k.children.length;c++)k.children[c].style.display=c===a?"block":"none";g=a}function e(){return performance&&performance.now?performance.now():Date.now()}var g=0,k=document.createElement("div");k.style.cssText="position:fixed;top:0;left:0;cursor:pointer;opacity:0.9;z-index:10000";
k.addEventListener("click",function(a){a.preventDefault();b(++g%k.children.length)},!1);var p=e(),h=p,t=0,x=c(new a.Panel("FPS","#0ff","#002")),z=c(new a.Panel("MS","#0f0","#020"));if(self.performance&&self.performance.memory)var v=c(new a.Panel("MB","#f08","#201"));b(0);return{REVISION:16,dom:k,addPanel:c,showPanel:b,begin:function(){p=e()},end:function(){t++;var a=e();z.update(a-p,200);if(a>=h+1E3&&(x.update(1E3*t/(a-h),100),h=a,t=0,v)){var c=performance.memory;v.update(c.usedJSHeapSize/1048576,
c.jsHeapSizeLimit/1048576)}return a},update:function(){p=this.end()},domElement:k,setMode:b}};a.Panel=function(a,b,e){var g=Infinity,k=0,p=Math.round,h=p(window.devicePixelRatio||1),t=80*h,x=48*h,z=3*h,v=2*h,u=3*h,s=15*h,r=74*h,w=30*h,q=document.createElement("canvas");q.width=t;q.height=x;q.style.cssText="width:80px;height:48px";var f=q.getContext("2d");f.font="bold "+9*h+"px Helvetica,Arial,sans-serif";f.textBaseline="top";f.fillStyle=e;f.fillRect(0,0,t,x);f.fillStyle=b;f.fillText(a,z,v);f.fillRect(u,
s,r,w);f.fillStyle=e;f.globalAlpha=0.9;f.fillRect(u,s,r,w);return{dom:q,update:function(y,x){g=Math.min(g,y);k=Math.max(k,y);f.fillStyle=e;f.globalAlpha=1;f.fillRect(0,0,t,s);f.fillStyle=b;f.fillText(p(y)+" "+a+" ("+p(g)+"-"+p(k)+")",z,v);f.drawImage(q,u+h,s,r-h,w,u,s,r-h,w);f.fillRect(u+r-h,s,h,w);f.fillStyle=e;f.globalAlpha=0.9;f.fillRect(u+r-h,s,h,p((1-y/x)*w))}}};return a});function Observable(){this.observers=[]}Observable.prototype.addObserver=function(a){this.observers.push(a)};Observable.prototype.removeObserver=function(a){a=this.observers.indexOf(a);~a&&this.observers.splice(a,1)};Observable.prototype.hasObserver=function(a){return~this.observers.indexOf(a)?!0:!1};Observable.prototype.notifyObservers=function(){for(var a=this.observers.length-1;0<=a;a--)this.observers[a].apply(null,arguments)};Math.sign||(Math.__proto__.sign=function(a){return isNaN(a)?NaN:0===a?a:0<a?1:-1});function vectorLength(a,c){return Math.sqrt(a*a+c*c)}function RK41DObject_State(a,c){this.u=a;this.s=c}function RK41DObject_Derivative(a,c){this.du=a;this.ds=c}function RK41DObject(){this.state=new RK41DObject_State(0,0)}
RK41DObject.prototype.evaluate=function(a,c,b,e){if("undefined"==typeof b)return new RK41DObject_Derivative(a.s,this.acceleration(a,c));a=new RK41DObject_State(a.u+e.du*b,a.s+e.ds*b);return new RK41DObject_Derivative(a.s,this.acceleration(a,c+b))};
RK41DObject.prototype.integrate=function(a,c){var b=this.evaluate(this.state,a),e=this.evaluate(this.state,a,0.5*c,b),g=this.evaluate(this.state,a,0.5*c,e),k=this.evaluate(this.state,a,c,g),p=1/6*(b.ds+2*(e.ds+g.ds)+k.ds);this.state.u+=1/6*(b.du+2*(e.du+g.du)+k.du)*c;this.state.s+=p*c};function normalizeRadian(a){for(;a>2*Math.PI;)a-=2*Math.PI;for(;0>a;)a+=2*Math.PI;return a}function Cannon(){RK41DObject.call(this);this.state.u=0;this.state.s=Math.PI/3}Cannon.prototype=new RK41DObject;
Cannon.prototype.constructor=RK41DObject;Cannon.prototype.acceleration=function(a,c){return 0};Cannon.prototype.getAngle=function(){return this.state.u+Math.PI/2};Cannon.prototype.update=function(a,c){this.integrate(a,c);Math.abs(this.state.u)>=Math.PI/2&&(this.state.u=(Math.PI/2-Math.abs(Math.PI/2-Math.abs(this.state.u)))*Math.sign(this.state.u),this.state.s*=-1)};
function Ball(a,c,b,e){RK41DObject.call(this);this.nr=a;this.nx=c;this.ny=b;this.direction=e;this.state.u=0;this.state.s=1;this.counter=3}Ball.prototype=new RK41DObject;Ball.prototype.constructor=RK41DObject;Ball.prototype.acceleration=function(a,c){return-0.4};Ball.prototype.update=function(a,c,b){var e=this.state.u;this.integrate(a,c);a=this.state.u-e;this.nx+=a*Math.cos(this.direction);this.ny+=a*Math.sin(this.direction);this.bounce(b)};
Ball.prototype.bounce=function(a){this.nx>1-this.nr?(this.nx=1-this.nr,this.direction=normalizeRadian(Math.PI-this.direction)):this.nx<this.nr&&(this.nx=this.nr,this.direction=normalizeRadian(Math.PI-this.direction));this.ny>1-this.nr&&(this.ny=1-this.nr,this.direction=normalizeRadian(-this.direction));for(var c=0;c<a.length;++c){var b=a[c],e=this.nx-b.nx,g=this.ny-b.ny,k=vectorLength(e,g);k<=b.nr+this.nr&&(--b.counter,this.nx=b.nx+e*(this.nr+b.nr)/k,this.ny=b.ny+g*(this.nr+b.nr)/k,e=Math.atan2(g,
e),g=this.direction,k=this.state.s,b=-k*Math.cos(g-e)*Math.cos(e)+k*Math.sin(g-e)*Math.cos(e+Math.PI/2),e=-k*Math.cos(g-e)*Math.sin(e)+k*Math.sin(g-e)*Math.sin(e+Math.PI/2),this.direction=Math.atan2(e,b))}};Ball.prototype.grow=function(a){for(var c=Number.MAX_VALUE,b,e=0;e<a.length;++e)b=a[e],b=vectorLength(this.nx-b.nx,this.ny-b.ny)-b.nr,c>b&&(c=b);b=this.nx;c>b&&(c=b);b=1-this.nx;c>b&&(c=b);b=Math.abs(this.ny);c>b&&(c=b);b=Math.abs(1-this.ny);c>b&&(c=b);this.nr=Math.abs(c)};
function DontYouFillItGame(){this.state=this.PAUSED();this.cannon=new Cannon;this.staticBalls=[];this.currentBall=null;this.lastUpdateTime=performance.now?performance.now():Date.now();this.score=0}DontYouFillItGame.prototype.PAUSED=function(){return 1};DontYouFillItGame.prototype.RUNNING=function(){return 2};DontYouFillItGame.prototype.GAMEOVER=function(){return 3};
DontYouFillItGame.prototype.update=function(a){if(this.currentBall)for(var c=this.lastUpdateTime,b=Math.floor(a-this.lastUpdateTime),e,g=1;g<=b;++g){e=(this.lastUpdateTime*(b-g)+a*g)/b;this.currentBall.update(c/1E3,(e-c)/1E3,this.staticBalls);for(c=this.staticBalls.length-1;0<=c;--c)0==this.staticBalls[c].counter&&(++this.score,this.staticBalls.splice(c,1));if(this.currentBall.ny<this.currentBall.nr&&normalizeRadian(this.currentBall.direction)>Math.PI)this.currentBall.state.s=0,this.state=this.GAMEOVER();
else if(0.001>this.currentBall.state.s){0<=this.currentBall.ny&&(this.currentBall.grow(this.staticBalls),this.staticBalls.push(this.currentBall));this.currentBall=null;break}c=e}this.cannon.update(this.lastUpdateTime/1E3,(a-this.lastUpdateTime)/1E3);this.lastUpdateTime=a};DontYouFillItGame.prototype.pause=function(){this.state=this.PAUSED()};DontYouFillItGame.prototype.resume=function(){this.lastUpdateTime=performance.now?performance.now():Date.now();this.state=this.RUNNING()};
DontYouFillItGame.prototype.reset=function(){this.currentBall=null;this.staticBalls=[];this.score=this.cannon.state.u=0;this.resume()};DontYouFillItGame.prototype.fire=function(){this.currentBall=new Ball(0.025,0.5+Math.cos(this.cannon.getAngle())/15,-1/6+1/15+Math.sin(this.cannon.getAngle())/15,this.cannon.getAngle())};function DontYouFillItCanvasGui(a,c){function b(a){return a}function e(a){a.moveTo(arguments[1],arguments[2]);for(var c=3;c<arguments.length;c+=2)a.lineTo(arguments[c],arguments[c+1])}function g(a,c){var f=c.nx*l,g=-c.ny*l,m=c.nr*l,n=32<m?Math.floor:b,k=32<m?Math.ceil:b;a.fillStyle="white";a.strokeStyle="white";a.lineWidth=1;a.beginPath();a.arc(f,g,m,0,2*Math.PI,!1);if(1==c.counter){var h=n(f-0.2*m),p=k(f+0.2*m),f=n(g-0.7*m),q=k(g+0.7*m);e(a,h,f,h,q,p,q,p,f)}else if(2==c.counter){var h=n(f-0.5*m),
p=n(f-0.1*m),r=k(f+0.1*m),u=k(f+0.5*m),f=n(g-0.7*m),q=n(g-0.3*m),n=n(g-0.15*m),s=k(g+0.15*m),v=k(g+0.3*m),g=k(g+0.7*m);e(a,u,f,h,f,h,q,r,q,r,n,h,n,h,g,u,g,u,v,p,v,p,s,u,s)}else 3==c.counter&&(h=n(f-0.5*m),p=k(f+0.1*m),r=k(f+0.5*m),f=n(g-0.7*m),q=n(g-0.3*m),n=n(g-0.15*m),s=k(g+0.15*m),v=k(g+0.3*m),g=k(g+0.7*m),e(a,r,f,h,f,h,q,p,q,p,n,h,n,h,s,p,s,p,v,h,v,h,g,r,g));a.closePath();a.fill()}function k(a){v.androidStockCompat?(a.clearRect(0,0,a.canvas.width,a.canvas.height),a.canvas.style.display="none",
a.canvas.offsetHeight,a.canvas.style.display="inherit"):a.clearRect(0,0,a.canvas.width,a.canvas.height)}function p(d){v.observable.notifyObservers("beginStep");a.state==a.RUNNING()&&a.update(d);if(v.state==v.GAME){if(s||void 0===A||A.score!=a.score){d=r;d.fillStyle="black";d.fillRect(0,0,d.canvas.width,d.canvas.height);d.fillStyle="white";d.textAlign="left";d.textBaseline="bottom";d.font=M;d.fillText("Highscore",C,B-l/12+l/120);d.fillText("Score",C,B);var b=d.measureText("Highscore ").width;d.fillText(c,
C+b,B-l/12+l/120);d.fillText(a.score,C+b,B)}if(s){d=w;d.fillStyle="black";d.fillRect(0,0,d.canvas.width,d.canvas.height);var b=Math.floor(0.1*(l/6)),e=Math.floor(0.6*(l/6)),h=Math.floor(0.1*(l/6)),m=Math.floor(0.3*(l/6)),n=Math.floor(0.8*(l/6));d.fillStyle="white";d.fillRect(b,h,m,n);d.fillRect(e,h,m,n)}if(void 0!=A)for(d=0;d<A.previousBalls.length;++d)b=A.previousBalls[d],0==b.counter&&(u.push(b.ctx),delete b.ctx);for(d=0;d<a.staticBalls.length;++d){b=a.staticBalls[d];n=b.nr*l;e=Math.floor(b.nx*
l-n-1);h=Math.floor(-b.ny*l-n-1);m=!1;if(s||void 0===b.ctx){void 0===b.ctx&&(0==u.length?(b.ctx=document.createElement("canvas").getContext("2d"),b.ctx.canvas.classList.add("ball"),F.appendChild(b.ctx.canvas)):b.ctx=u.pop());var n=Math.ceil(2*n)+2,t=b.ctx.canvas;if(t.width!=n||t.height!=n)t.width=n,t.height=n,m=!0;b.ctx.canvas.style.left=e-1+"px";b.ctx.canvas.style.top=l-1+h+"px";b.ctx.canvas.style.display="block"}if(s||void 0===b.was||b.was!=b.counter)b.was=b.counter,b.ctx.setTransform(1,0,0,1,0,
0),m||k(b.ctx),b.ctx.translate(-e,-h),g(b.ctx,b)}for(d=0;d<u.length;++d)"none"!=u[d].canvas.style.display&&(u[d].canvas.style.display="none");s=!1;k(q);q.setTransform(1,0,0,1,0,0);q.translate(-l/2+H/2,-I+J);d=q;b=Math.round(R/2);e=Math.round(l/2);h=e-b;m=e+b;n=Math.round(K+l/6);t=Math.round(K+l/6-N);d.lineWidth=L;d.fillStyle="white";d.strokeStyle="white";d.lineCap="butt";d.beginPath();d.moveTo(h,n);d.lineTo(h,t);d.arc(e,t,b,Math.PI,0);d.lineTo(m,n);d.closePath();d.fill();d.beginPath();d.moveTo(e,
t);d.lineTo(e+Math.cos(a.cannon.getAngle())*G,t-Math.sin(a.cannon.getAngle())*G);d.closePath();d.stroke();q.setTransform(1,0,0,1,0,0);a.currentBall?(b=a.currentBall.nr*l,d=Math.floor(a.currentBall.nx*l-b-O),b=Math.floor(-a.currentBall.ny*l-b-O),f.setTransform(1,0,0,1,0,0),k(f),f.save(),f.translate(-d,-b),g(f,a.currentBall),f.restore(),f.canvas.style.left=D+Math.floor(C)+d+"px",f.canvas.style.top=E+Math.floor(K)+b+"px",f.canvas.style.display="block"):f.canvas.style.display="none";A={previousBalls:a.staticBalls.slice(),
score:a.score}}v.observable.notifyObservers("endStep");if(a.state==a.RUNNING())window.requestAnimationFrame(p);else if(a.state==a.GAMEOVER()){c=Math.max(a.score,c);v.observable.notifyObservers("gameover",a.score);for(d=0;d<a.staticBalls.length;++d)u.push(a.staticBalls[d].ctx),delete a.staticBalls[d].ctx}}function h(){a.state==a.RUNNING()&&(a.pause(),v.observable.notifyObservers("pause"))}function t(){var b=y.clientWidth,c=y.clientHeight;P=l=0.75>b/c?b:Math.floor(0.75*c);I=Math.floor(4/3*l);E=Math.floor((c-
I)/2);D=Math.floor((b-P)/2);B=Math.floor(l/6);K=B+l;C=0;R=l/10;N=l/15;G=l/15;L=l/18;Q=Math.ceil(l/20)+2*O;b=Math.sqrt(L/2*(L/2)+G*G);H=Math.ceil(2*b);J=Math.ceil(N+b);M=Math.floor(l/12)+"px Arial";r.font=M;r.canvas.width=Math.ceil(r.measureText("Highscore XXXX").width);r.canvas.height=Math.ceil(l/6);r.canvas.style.left=D+"px";r.canvas.style.top=E+"px";w.canvas.width=Math.ceil(l/6);w.canvas.height=Math.ceil(l/6);w.canvas.style.left=D+P-Math.ceil(l/6)+"px";w.canvas.style.top=E+"px";q.canvas.width=H;
q.canvas.height=J;q.canvas.style.left=Math.ceil(D+(l-H)/2)+"px";q.canvas.style.top=Math.floor(E+I-J)+"px";f.canvas.width=Q;f.canvas.height=Q;F.style.width=l-2+"px";F.style.height=l-2+"px";F.style.left=D+"px";F.style.top=E+B+"px";s=!0;a.state!=a.RUNNING()&&window.requestAnimationFrame(p)}function x(a){if(500>a.timeStamp-S)return!0;S=a.timeStamp;return!1}function z(a,b){var c="string"===typeof a?document.getElementById(a):a;c.addEventListener("click",b);c.addEventListener("touchstart",b,supportsPassive?
{passive:!1}:!1)}var v=this,u=[],s=!0;this.MENU=1;this.GAME=2;this.state=this.MENU;this.game=a;this.observable=new Observable;var r=document.getElementById("ScoreCanvas").getContext("2d"),w=document.getElementById("PauseCanvas").getContext("2d"),q=document.getElementById("CannonCanvas").getContext("2d"),f=document.getElementById("BallCanvas").getContext("2d"),y=r.canvas.parentNode,F=document.getElementById("Balls"),S=0,A=void 0,l,P,I,E,D,K,B,C,R,N,G,L,H,J,Q,O=8,M;window.addEventListener("resize",
t,!1);z("PauseCanvas",function(a){a.preventDefault();a.stopPropagation();x(a)||h()});z(y,function(b){b.preventDefault();x(b)||null==a.currentBall&&a.state==a.RUNNING()&&a.fire()});document.addEventListener("visibilitychange",function(){document.hidden&&h()},!1);this.resume=function(){a.resume();this.state=this.GAME;window.requestAnimationFrame(p)};this.reset=function(){A=void 0;a.reset();window.requestAnimationFrame(p)};t();window.requestAnimationFrame(p)}
DontYouFillItCanvasGui.prototype.addObserver=function(a){this.observable.addObserver(a)};DontYouFillItCanvasGui.prototype.removeObserver=function(a){this.observable.removeObserver(a)};DontYouFillItCanvasGui.prototype.hasObserver=function(a){return this.observable.hasObserver(a)};DontYouFillItCanvasGui.prototype.notifyObservers=function(){this.observable.notifyObservers()};var game=new DontYouFillItGame,gui=new DontYouFillItCanvasGui(game,parseInt(localStorage.getItem("highscore"),10)||0),stats=new Stats;stats.showPanel(0);stats.dom.style.removeProperty("top");stats.dom.style.position="fixed";stats.dom.style.left="0px";stats.dom.style.bottom="0px";stats.dom.style.display="none";document.body.appendChild(stats.dom);function statsObserver(a){"beginStep"==a?stats.begin():"endStep"==a&&stats.end()}
function setStockCompatibilityMode(a){localStorage.setItem("stockCompatibility",a);gui.androidStockCompat=a}function setDebugMode(a){localStorage.setItem("debug",a);a?(stats.dom.style.display="block",gui.addObserver(statsObserver)):(stats.dom.style.display="none",gui.removeObserver(statsObserver))}function asBool(a){return!0===a||"true"===a}var query_string={};window.location.search.substring(1).split("&").forEach(function(a){a=a.split("=",2);query_string[a[0]]=2==a.length?a[1]:!0});
void 0!==query_string.stock?setStockCompatibilityMode(asBool(query_string.stock)):null!==localStorage.getItem("stockCompatibility")?setStockCompatibilityMode(asBool(localStorage.getItem("stockCompatibility"))):setStockCompatibilityMode(!1);void 0!==query_string.debug?setDebugMode(asBool(query_string.debug)):null!==localStorage.getItem("debug")?setDebugMode(asBool(localStorage.getItem("debug"))):setDebugMode(!1);
var screenContainer=document.getElementById("screenContainer"),startScreen=document.getElementById("startScreen"),optionsScreen=document.getElementById("optionsScreen"),pauseScreen=document.getElementById("pauseScreen"),gameoverScreen=document.getElementById("gameoverScreen"),licenseScreen=document.getElementById("licenseScreen"),screens=[];
function pushScreen(a){0!=screens.length&&(screens[screens.length-1].style.display="none");screens.push(a);a.style.zIndex=screens.length;a.style.visibility="hidden";a.style.display="block";a.scrollTop=0;a.style.visibility="visible";screenContainer.style.display="block";screenContainer.style.backgroundColor=a==pauseScreen?"rgba(0, 0, 0, 0.85)":"black"}
function popScreen(){0!=screens.length&&(screens.pop().style.display="none",0==screens.length?screenContainer.style.display="none":screens[screens.length-1].style.display="block")}function popAllScreens(){for(;0<screens.length;)screens.pop().style.display="none";screenContainer.style.display="none"}document.getElementById("startScreenPlayButton").addEventListener("click",function(a){a.preventDefault();gui.resume();popAllScreens()});
document.getElementById("startScreenOptionsButton").addEventListener("click",function(a){a.preventDefault();optionsScreen.init();pushScreen(optionsScreen)});document.getElementById("optionsScreenBackButton").addEventListener("click",function(a){a.preventDefault();popScreen()});document.getElementById("pauseScreenContinueButton").addEventListener("click",function(a){a.preventDefault();gui.resume();popScreen()});
document.getElementById("pauseScreenOptionsButton").addEventListener("click",function(a){a.preventDefault();pushScreen(optionsScreen)});document.getElementById("gameoverScreenPlayAgainButton").addEventListener("click",function(a){a.preventDefault();gui.reset();popAllScreens()});document.getElementById("startScreenLicenseButton").addEventListener("click",function(a){a.preventDefault();pushScreen(licenseScreen)});
document.getElementById("licenseScreenBackButton").addEventListener("click",function(a){a.preventDefault();popScreen();licenseScreen.reset()});document.getElementById("compatibilityModeCheckbox").addEventListener("change",function(a){setStockCompatibilityMode(a.target.checked)});document.getElementById("framerateCheckbox").addEventListener("change",function(a){setDebugMode(a.target.checked)});gui.addObserver(function(a){"pause"==a&&pushScreen(pauseScreen)});
gui.addObserver(function(a,c){if("gameover"==a){var b=parseInt(localStorage.getItem("highscore"),10)||0;(b=c>b)&&localStorage.setItem("highscore",c.toString(10));document.getElementById("gameoverScreenScoreMessage").style.display=b?"none":"inline";document.getElementById("gameoverScreenHighscoreMessage").style.display=b?"inline":"none";document.getElementById("gameoverScreenScore").innerHTML=c;pushScreen(gameoverScreen)}});pushScreen(startScreen);
function setNodeText(a,c){var b=a.firstChild;do if(3==b.nodeType){b.nodeValue=c;break}while(b=b.nextSibling)}
Array.prototype.forEach.call(document.getElementsByClassName("hideable"),function(a){var c=function(b){Array.prototype.forEach.call(document.getElementsByClassName(a.getAttribute("data-toggle")),b)};a.reset=function(){this.style.display="none";c(function(a){setNodeText(a,"[-]")})};c(function(b){b.addEventListener("click",function(b){var g="none"!=a.style.display;c(function(a){setNodeText(a,g?"[+]":"[-]")});a.style.display=g?"none":"block";b.preventDefault()})});a.style.display="none"});
optionsScreen.init=function(){document.getElementById("compatibilityModeCheckbox").checked=gui.androidStockCompat;document.getElementById("framerateCheckbox").checked=gui.hasObserver(statsObserver)};licenseScreen.reset=function(){Array.prototype.forEach.call(this.getElementsByClassName("hideable"),function(a){a.reset()})};
